'use strict';

export const GETSNIPPETDATA = "GETSNIPPETDATA";
export const SETSNIPPETDATA = "SETSNIPPETDATA";

export const ADDSNIPPETDATA = "ADDSNIPPETDATA";
export const UPDATESNIPPETDATA = "UPDATESNIPPETDATA";
export const DELETESNIPPETDATA = "DELETESNIPPETDATA";

export const SETCURRENTSNIPPETDATA = "SETCURRENTSNIPPETDATA";

export const ADDTAG = "ADDTAG";
export const REMOVETAG ="REMOVETAG";
export const SETTAGANDOR = "SETTAGANDOR";

export const SETLANGUAGE = "SETLANGUAGE";

export const SETERROR = "SETERROR";