export const GETSNIPPETDATA = "GETSNIPPETDATA";
export const SETSNIPPETDATA = "SETSNIPPETDATA";

export const ADDSNIPPETDATA = "ADDSNIPPETDATA";
export const REMOVESNIPPETDATA = "REMOVESNIPPETDATA";

export const SETCURRENTSNIPPETDATA = "SETCURRENTSNIPPETDATA";

export const ADDTAG = "ADDTAG";
export const REMOVETAG ="REMOVETAG";

export const MYSNIPPETS="MYSNIPPETS";
export const ALLSNIPPETS="ALLSNIPPETS";


export const SETLANGUAGE = "SETLANGUAGE";