export const GETSNIPPETDATA = "GETSNIPPETDATA";
export const SETSNIPPETDATA = "SETSNIPPETDATA";

export const ADDSNIPPETDATA = "ADDSNIPPETDATA";
export const DELETESNIPPETDATA = "DELETESNIPPETDATA";

export const SETCURRENTSNIPPETDATA = "SETCURRENTSNIPPETDATA";

export const ADDTAG = "ADDTAG";
export const REMOVETAG ="REMOVETAG";

export const SETLANGUAGE = "SETLANGUAGE";